name: Build Topic Suggestion PDF
on: [push, pull_request]
jobs:
  build_topic_suggestion_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: topic-suggestion.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: topic-suggestion.pdf
